import { search } from 'node-emoji'
/**
 * Regenerates `src/lib/emoji-map.generated.ts`.
 *
 * `node-emoji` is a devDependency, not a runtime one: it pulls in
 * `emojilib`, whose payload is dominated by the search keywords behind
 * `find` / `search`. Bundled, that is 227 kB minified — eleven times the
 * whole library — to do one thing, turn `:rocket:` into 🚀.
 *
 * The pairs are emitted as one space-delimited string rather than an
 * object literal. An object literal of this size is built property by
 * property when the module is evaluated, which every page pays for even
 * when it only ever renders a profile card. A string is one allocation,
 * and `src/lib/emoji.ts` turns it into a Map the first time a shortcode
 * actually turns up.
 *
 * Run with `bun run gen:emoji` after bumping `node-emoji`.
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const pairs = search('')
  .map(({ name, emoji }) => [name, emoji] as const)
  .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))

// The encoding is positional, so a space anywhere inside a name or an
// emoji would silently shift every pair after it.
for (const [name, emoji] of pairs) {
  if (/\s/.test(name) || /\s/.test(emoji)) {
    throw new Error(`Whitespace in emoji pair, which the encoding cannot carry: ${name}`)
  }
}

const data = pairs.map(([name, emoji]) => `${name} ${emoji}`).join(' ')

const source = `/* Generated by scripts/generate-emoji-map.ts — do not edit. */

/**
 * Every GitHub shortcode and its emoji, as \`name emoji name emoji …\`.
 *
 * Decoded lazily by \`src/lib/emoji.ts\`. See the generator for why this
 * is a string and not an object.
 */
export const EMOJI_DATA =
  '${data}'
`

const target = resolve(import.meta.dir, '../src/lib/emoji-map.generated.ts')
writeFileSync(target, source)

console.log(`wrote ${pairs.length} shortcodes (${data.length} chars) to ${target}`)
