import { search } from 'node-emoji'
/**
 * Regenerates `src/lib/emoji-map.generated.ts`.
 *
 * `node-emoji` is a devDependency, not a runtime one: it pulls in
 * `emojilib`, whose payload is dominated by the search keywords behind
 * `find` / `search`. Bundled, that is 227 kB minified — eleven times the
 * whole library — to do one thing, turn `:rocket:` into 🚀.
 *
 * This script extracts just the shortcode-to-emoji pairs and writes them
 * out as a plain object. Coverage is identical; the weight is not.
 *
 * Run with `bun run gen:emoji` after bumping `node-emoji`.
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const pairs = search('')
  .map(({ name, emoji }) => [name, emoji] as const)
  .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))

const body = pairs.map(([name, emoji]) => `  '${name}': '${emoji}',`).join('\n')

const source = `/* Generated by scripts/generate-emoji-map.ts — do not edit. */

/** Every GitHub shortcode, mapped to its unicode emoji. */
export const EMOJI: Readonly<Record<string, string>> = {
${body}
}
`

const target = resolve(import.meta.dir, '../src/lib/emoji-map.generated.ts')
writeFileSync(target, source)

console.log(`wrote ${pairs.length} shortcodes to ${target}`)
